aris_input: "data_raw/aris"
aris_extract: "data_processed/aris"

aris_to_polar_method: "polar2+csv"  # polar1, polar2, csv, combine with +
aris_to_polar_png_compression: 9

aris_optical_flow_out: "data_processed/aris"
aris_optical_flow_method: "lk"  # lk, farnerback
aris_optical_flow_recalc: "True"


gantry_input: "data_raw/gantry"
gantry_extract: "data_processed/gantry"
gantry_time_adjust: "+2"


gopro_clips: "data_processed/gopro/sd"
gopro_optical_flow_method: "lk"  # lk, farnerback
gopro_optical_flow_recalc: "True"