INCLUDES=-I ../../aris-file-sdk/type-definitions/C -I ../../aris-file-sdk/common-code
SOURCES=./extract_full.cpp ../../aris-file-sdk/common-code/FrameFuncs.c

extractfull: $(SOURCES)
	gcc -o extract_aris_full $(SOURCES) $(INCLUDES)
