# Preprocessing
aris_input: "../data_raw/aris"
aris_extract: "../data_processed/aris"
aris_to_polar_method: "polar2"  # polar1, polar2, csv, combine with +
aris_to_polar_png_compression: 9
aris_to_polar_polar1_norm_intensity: False
aris_to_polar_polar1_antialiasing: False
aris_to_polar_polar1_scale: 2.0
aris_to_polar_polar2_resolution: 500
aris_optical_flow_method: "lk"  # lk, farnerback
aris_optical_flow_recalc: "True"

gantry_input: "../data_raw/gantry"
gantry_extract: "/data_processed/gantry"
gantry_time_adjust: "+2"

gopro_clips: "../data_processed/gopro/sd"
gopro_optical_flow_method: "lk"  # lk, farnerback
gopro_optical_flow_recalc: True


# Data matching
match_file: "../data_processed/matches.csv"


# Export
export_dir: "../data_export"
export_gopro_resolution: "fhd"
export_gopro_format: "jpg"
export_only_with_gopro: True